[package]
name = "rocket-svc"
version = "0.1.0"
authors = ["Deependra Ariyadewa <deependra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
