name: Rocket SVC Rust

on: [push]

jobs:
  build:

    runs-on: rustlang/rust:nightly

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
